[health_setting]
health_insurance_premium_rate = 5.17 #(%)
employee_contribution_rate = 30 #(%)

# 投保金額分級表

[[health_insurance_group]]
id = 1
cost = 1200
min = 0
max = 28800
levels = [
    { id = 1, min = 0, max = 27470, insurance_salary = 27470 },
    { id = 2, min = 27471, max = 27600, insurance_salary = 27600 },
    { id = 3, min = 27601, max = 28800, insurance_salary = 28800 }
]

[[health_insurance_group]]
id = 2
cost = 1500
min = 28801
max = 34800
levels = [
    { id = 4, min = 28801, max = 30300, insurance_salary = 30300 },
    { id = 5, min = 30301, max = 31800, insurance_salary = 31800 },
    { id = 6, min = 31801, max = 33300, insurance_salary = 33300 },
    { id = 7, min = 33301, max = 34800, insurance_salary = 34800 }
]

[[health_insurance_group]]
id = 3
cost = 1900
min = 34801
max = 43900
levels = [
    { id = 9, min = 34801, max = 36300, insurance_salary = 36300 },
    { id = 10, min = 36301, max = 38200, insurance_salary = 38200 },
    { id = 11, min = 38201, max = 40100, insurance_salary = 40100 },
    { id = 12, min = 40101, max = 42000, insurance_salary = 42000 },
    { id = 13, min = 42001, max = 43900, insurance_salary = 43900 }
]

[[health_insurance_group]]
id = 4
cost = 2400
min = 45801
max = 57800
levels = [
    { id = 14, min = 45801, max = 48200, insurance_salary = 48200 },
    { id = 15, min = 48201, max = 50600, insurance_salary = 50600 },
    { id = 16, min = 50601, max = 53000, insurance_salary = 53000 },
    { id = 17, min = 53001, max = 55400, insurance_salary = 55400 },
    { id = 18, min = 55401, max = 57800, insurance_salary = 57800 }
]

[[health_insurance_group]]
id = 5
cost = 3000
min = 57801
max = 72800
levels = [
    { id = 19, min = 57801, max = 60800, insurance_salary = 60800 },
    { id = 20, min = 60801, max = 63800, insurance_salary = 63800 },
    { id = 21, min = 63801, max = 66800, insurance_salary = 66800 },
    { id = 22, min = 66801, max = 69800, insurance_salary = 69800 },
    { id = 23, min = 69801, max = 72800, insurance_salary = 72800 }
]

[[health_insurance_group]]
id = 6
cost = 3700
min = 72801
max = 87600
levels = [
    { id = 24, min = 72801, max = 76500, insurance_salary = 76500 },
    { id = 25, min = 76501, max = 80200, insurance_salary = 80200 },
    { id = 26, min = 80201, max = 83900, insurance_salary = 83900 },
    { id = 27, min = 83901, max = 87600, insurance_salary = 87600 }
]

[[health_insurance_group]]
id = 7
cost = 4500
min = 87601
max = 110100
levels = [
    { id = 28, min = 87601, max = 92100, insurance_salary = 92100 },
    { id = 29, min = 92101, max = 96600, insurance_salary = 96600 },
    { id = 30, min = 96601, max = 101100, insurance_salary = 101100 },
    { id = 31, min = 101101, max = 105600, insurance_salary = 105600 },
    { id = 32, min = 105601, max = 110100, insurance_salary = 110100 }
]

[[health_insurance_group]]
id = 8
cost = 5400
min = 110101
max = 150000
levels = [
    { id = 33, min = 110101, max = 115500, insurance_salary = 115500 },
    { id = 34, min = 115501, max = 120900, insurance_salary = 120900 },
    { id = 35, min = 120901, max = 126300, insurance_salary = 126300 },
    { id = 36, min = 126301, max = 131700, insurance_salary = 131700 },
    { id = 37, min = 131701, max = 137100, insurance_salary = 137100 },
    { id = 38, min = 137101, max = 142500, insurance_salary = 142500 },
    { id = 39, min = 142501, max = 147900, insurance_salary = 147900 },
    { id = 40, min = 147901, max = 150000, insurance_salary = 150000 }
]

[[health_insurance_group]]
id = 9
cost = 6400
min = 150001
max = 182000
levels = [
    { id = 41, min = 150001, max = 156400, insurance_salary = 156400 },
    { id = 42, min = 156401, max = 162800, insurance_salary = 162800 },
    { id = 43, min = 162801, max = 169200, insurance_salary = 169200 },
    { id = 44, min = 169201, max = 175600, insurance_salary = 175600 },
    { id = 45, min = 175601, max = 182000, insurance_salary = 182000 }
]

[[health_insurance_group]]
id = 10
cost = 7500
min = 182001
max = 9999999
levels = [
    { id = 46, min = 182001, max = 189500, insurance_salary = 189500 },
    { id = 47, min = 189501, max = 197000, insurance_salary = 197000 },
    { id = 48, min = 197001, max = 204500, insurance_salary = 204500 },
    { id = 49, min = 204501, max = 212000, insurance_salary = 212000 },
    { id = 50, min = 212001, max = 9999999, insurance_salary = 219500 }
]
